name: space_shooter
description: Retro Fun Crate - A premium collection of 20+ unique retro arcade games.
publish_to: 'none'
version: 1.1.2+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.14.0
  collection: ^1.18.0
  shared_preferences: ^2.2.2
  vector_math: ^2.1.4
  flutter_displaymode: ^0.7.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
