export const projects = [
  { id: 1, title: "Full-Stack SaaS App", type: "Main Project", desc: "Auth, dashboard, database. Productivity tracker, invoicing tool." },
  { id: 2, title: "E-Commerce Website", type: "Business", desc: "Product listings, cart, checkout, payment integration." },
  { id: 3, title: "Job Board / Job Portal", type: "Business", desc: "Post jobs, apply, filters. Relatable to recruiters." },
  { id: 4, title: "Social Media App (Mini)", type: "Business", desc: "Posts, likes, comments. Mini Twitter." },
  { id: 5, title: "Admin Dashboard", type: "Business", desc: "Charts, analytics, user management. Clean UI." },
  { id: 6, title: "Developer Tool", type: "Problem-Solving", desc: "JSON formatter, Markdown previewer." },
  { id: 7, title: "API Project", type: "Problem-Solving", desc: "Weather, quotes, finance data custom API." },
  { id: 8, title: "URL Shortener", type: "Problem-Solving", desc: "Like bit.ly. Backend + database skills." },
  { id: 9, title: "Real-Time Chat App", type: "Problem-Solving", desc: "WebSockets, Messaging system." },
  { id: 10, title: "Task Management App", type: "Problem-Solving", desc: "Drag & drop (like Trello). Multiple users, boards." },
  { id: 11, title: "AI-Powered Web App", type: "Niche", desc: "Use AI APIs. Resume analyzer, chatbot." },
  { id: 12, title: "Portfolio Builder Tool", type: "Niche", desc: "Let users create their own portfolio." },
  { id: 13, title: "Expense Tracker", type: "Niche", desc: "Analytics, charts, reports, categories." },
  { id: 14, title: "Learning Platform", type: "Niche", desc: "Courses, progress tracking." },
  { id: 15, title: "Bug Tracker / Issue Tracker", type: "Niche", desc: "Like a mini Jira. Great for dev roles." },
  { id: 16, title: "Booking System", type: "Real-World", desc: "Hotel / doctor / appointment booking." },
  { id: 17, title: "Food Delivery UI + Backend", type: "Real-World", desc: "Like Uber Eats." },
  { id: 18, title: "Event Management Platform", type: "Real-World", desc: "Create/join events." },
  { id: 19, title: "Freelance Marketplace", type: "Real-World", desc: "Clients + freelancers." },
  { id: 20, title: "Blog Platform (CMS)", type: "Real-World", desc: "Write, edit, publish posts." },
  { id: 21, title: "Animated Landing Page", type: "Frontend", desc: "Smooth animations, modern UI/UX." },
  { id: 22, title: "Clone with Improvements", type: "Frontend", desc: "Rebuild Notion or dashboard UI." },
  { id: 23, title: "Dark/Light Mode UI System", type: "Frontend", desc: "Clean theme switching." },
  { id: 24, title: "Micro SaaS", type: "Advanced", desc: "Make $, built according to the new folder." }
,
  { id: 25, title: "AI Resume Analyzer", type: "AI", desc: "Upload resume -> get feedback + score + suggestions. Integrate OpenAI or similar APIs. Bonus: job-role matching" },
  { id: 26, title: "Job Tracker Dashboard", type: "Utility", desc: "Track applied jobs, status, notes. Kanban-style UI (like Trello). Add reminders & analytics" },
  { id: 27, title: "Real-Time Chat App", type: "App", desc: "Use WebSockets (Socket.io). Typing indicators, online status. Bonus: file sharing & emojis" },
  { id: 28, title: "Multi-Vendor E-commerce Platform", type: "Business", desc: "Seller dashboards + product management. Payment integration (Stripe). Admin analytics panel" },
  { id: 29, title: "SaaS Subscription App", type: "SaaS", desc: "User auth + billing. Feature gating based on plan" },
  { id: 30, title: "Collaborative Document Editor", type: "Productivity", desc: "Like Google Docs. Real-time sync (WebRTC / Firebase). Version history" },
  { id: 31, title: "AI Code Reviewer", type: "AI Tool", desc: "Paste code -> get suggestions. Highlight bugs & improvements" },
  { id: 32, title: "AI Study Assistant", type: "AI Tool", desc: "Upload notes -> generate summaries & quizzes. Flashcards auto-generation" },
  { id: 33, title: "AI Chatbot for Websites", type: "AI Tool", desc: "Embed chatbot widget. Train on custom data" },
  { id: 34, title: "Image Caption Generator", type: "AI Tool", desc: "Upload image -> generate captions. Use ML APIs or models" },
  { id: 35, title: "Developer Portfolio Builder", type: "Tool", desc: "Drag-and-drop portfolio generator. Export as static site" },
  { id: 36, title: "Advanced Dashboard UI", type: "UI", desc: "Charts, Dark mode, filters, responsive design" },
  { id: 37, title: "Interactive Data Visualization Tool", type: "Data", desc: "Upload CSV -> create charts dynamically" },
  { id: 38, title: "Notion-like Notes App", type: "Productivity", desc: "Rich text editor. Nested pages" },
  { id: 39, title: "Expense Tracker with Insights", type: "Finance", desc: "Categorize spending. Monthly analytics & charts" },
  { id: 40, title: "Habit Tracker", type: "Lifestyle", desc: "Streaks, reminders. Visual progress graphs" },
  { id: 41, title: "URL Shortener (like Bitly)", type: "Tool", desc: "Short links + analytics. Click tracking" },
  { id: 42, title: "File Upload & Sharing App", type: "Utility", desc: "Secure file sharing with expiring links" },
  { id: 43, title: "Interview Prep Platform", type: "Education", desc: "Coding questions + timer. Mock interview mode" },
  { id: 44, title: "Roadmap Builder", type: "Education", desc: "Users create learning paths. Share with others" },
  { id: 45, title: "Event Booking System", type: "Business", desc: "Seat selection UI. Ticket generation" },
  { id: 46, title: "Online Code Playground", type: "Dev Tool", desc: "Run JS/Python in browser. Save & share snippets" },
  { id: 47, title: "Local Services Finder", type: "Marketplace", desc: "Like a mini marketplace. Location-based filtering" },
  { id: 48, title: "Fitness Tracker Dashboard", type: "Lifestyle", desc: "Workout logging + progress charts" },
  { id: 49, title: "Community Forum App", type: "Social", desc: "Threads, comments, voting system. Moderation tools" },
  { id: 50, title: "AI Mock Interviewer", type: "AI Tool", desc: "Ask questions, analyze answers. Give feedback + score. Bonus: speech-to-text + emotion detection" },
  { id: 51, title: "AI GitHub Project Explainer", type: "AI Tool", desc: "Input repo link -> explains codebase. Generates README, diagrams, and summaries" },
  { id: 52, title: "AI Bug Fix Assistant", type: "AI Tool", desc: "Paste error -> suggests fixes + explanation. Detects common issues automatically" },
  { id: 53, title: "AI Content Repurposer", type: "AI Tool", desc: "Input blog -> converts into Twitter threads, LinkedIn posts, YouTube scripts" },
  { id: 54, title: "AI Website UI Critic", type: "AI Tool", desc: "Upload screenshot -> get UX/UI feedback. Suggests layout & color improvements" },
  { id: 55, title: "AI Learning Path Generator", type: "AI Tool", desc: "Input goal -> Outputs structured roadmap + resources" },
  { id: 56, title: "AI Email Assistant", type: "AI Tool", desc: "Smart replies + tone adjustment. 'Make it formal / friendly / persuasive'" }
];
